### ISSUE TITLE
[RU] Minimal rust kernel. Target specification  have broken links

### ISSUE THREAD

**Issue by non-descriptive** [phil-opp/blog_os#1043]
Chapter [Target specification](https://os.phil-opp.com/ru/minimal-rust-kernel/#spetsifikatsiia-tselevoi-platformy)
```
[множество различных целевых троек][many different target triples] [поддержка платформы][platform-support]
```
two braced section. if I understand correctly how zola templates works it should be 
```
[множество различных целевых троек][platform-support]
```

Also 
```
[`wasm32-unknown-unknown` для WebAssembly] (https://www.hellorust.com/setup/wasm-target/).
```
broken and written as is, but my guess it's because of previous substitution errors.

**Comment by phil-opp** [comment]
Thanks for reporting! 



>  if I understand correctly how zola templates works it should be
> 
> ```
> [множество различных целевых троек][platform-support]
> ```

Yes, that looks correct.



> Also
> 
> ```
> [`wasm32-unknown-unknown` для WebAssembly] (https://www.hellorust.com/setup/wasm-target/).
> ```
> 
> broken and written as is, but my guess it's because of previous substitution errors.

It's probably because of the space between the `[...]` and `(...)` parts. 

I would be happy to merge a PR that fixes these errors. The relevant file is <https://github.com/phil-opp/blog_os/blob/main/blog/content/edition-2/posts/02-minimal-rust-kernel/index.ru.md>. I think it's possible to fix this directly on GitHub by clicking the pencil symbol to edit the file:

![image](https://user-images.githubusercontent.com/1131315/130358386-a38198ca-ce56-43ff-b7b4-c92058b74eb5.png)
