### ISSUE TITLE
`core::any::type_name` doesn't seem to work correctly

### ISSUE THREAD

**Issue by kelleyvanevert** [phil-opp/blog_os#1165]
In post 4, [Printing to the Console](https://os.phil-opp.com/testing/#insert-printing-automatically), you use the function `core::any::type_name` to print the name of the test function. It should print `trivial_assertion`, but in my case it prints `&dyn core::ops::function::Fn<()>+Output = ()`. So for example, after adding a few more test cases for the VGA buffer:

<img width="1076" alt="Screenshot 2022-10-24 at 17 07 50" src="https://user-images.githubusercontent.com/43432/197560367-d4e66df5-d1c2-48dc-a628-60be516f6493.png">

I followed the instructions of the previous posts to the letter, haven't diverged.

I'm not deep enough into Rust to understand why this might be different, but I'm hoping you know how to fix it :)

I'm using:
- rustc 1.66.0-nightly (7fcf850d7 2022-10-23)
- cargo 1.66.0-nightly (071eeaf21 2022-10-22)
- Mac M1

Let me know if I need to provide more details!

(Love the content, btw!! ❤️❤️ Keep it up)

**Comment by tsatke** [comment]
Want to share your code?
Works for me with `rustc 1.66.0-nightly (758f19645 2022-10-24)`.

**Comment by phil-opp** [comment]
I think the issue is that you missed the change to the `test_runner` signature:

```diff
- pub fn test_runner(tests: &[&dyn Fn()]) {
+ pub fn test_runner(tests: &[&dyn Testable]) {
``` 

The `&dyn Fn()` also implements the `Fn()` trait and thus also the `Testable` trait. So the run method still works without the above change, but `T` is just an anonymous `&dyn Fn()` in this case.

I pushed 1e2ae0e2 to highlight the signature change more because it's quite easy to miss.

> (Love the content, btw!! heartheart Keep it up)

Thanks! :)

**Comment by kelleyvanevert** [comment]
Ah! Thanks for the help! ❤️
