### ISSUE TITLE
AreaFrameAllocator no longer safe to use after remapping the kernel

### ISSUE THREAD

**Issue by mmalone** [phil-opp/blog_os#126]
The `AreaFrameAllocator` is unsafe to use after kernel remapping because it references the multiboot information structure, which is not remapped. I'm not sure what your next steps are (it's possible this is by design) but this took me a hot second to debug once I got through your last post and started off on my own adventures. If other people are having similar problems you have a couple choices:
- Stop using the AreaFrameAllocator and us some other FrameAllocator after the kernel remap
- Remap the multiboot header in `remap_the_kernel`, like you did the VGA buffer

You already have a reference to the `boot_info` object in remap_the_kernel, so you can use that for the remap. It's a bit ghetto, but here's a quick implementation of the latter option:

```rust
let boot_info_frame = Frame::containing_address(boot_info as *const _ as usize);
mapper.identity_map(boot_info_frame, PRESENT, allocator);
```

**Comment by phil-opp** [comment]
Thanks for the hint, I completely forgot this! We should really add this to the post and code.

I think it would fit best right _above_ the [Using the Correct Flags](http://os.phil-opp.com/remap-the-kernel.html#using-the-correct-flags) section (after we fixed the problem with printing). Maybe something like: „The same issue appears when we try to use the AreaFrameAllocator. The reason is that the multiboot info section is not mapped. To fix this, we identity map as well: [code]“.

What do you think?

**Comment by mmalone** [comment]
Yep, that makes sense. It's very similar to the VGA buffer problem so I think it'll flow nicely there. You could point out the code in `allocate_frame` that triggers an exception (dereferencing `current_area`, I believe). The &'static annotation in the `AreaFrameAllocator` should probably have been a red flag! It seems to me that anything that's marked &' static needs to be mapped and survive for the lifetime of the program otherwise you're lying to the compiler.

I'm new to rust, so I'm curious whether you think my code is the best approach to solving the problem. Is it safe to assume that the boot information structure fits in one page (probably not), that the reference doesn't use some sort of magic (like implementing `Deref`) that invalidates my type cast, etc? Alternatively, we could pass `multiboot_start` and `multiboot_end` into `remap_the_kernel`, but that clutters up the interface. With the VGA buffer the location and size is "general knowledge," but this seems to couple the `remap_the_kernel` function much more tightly to the rest of the kernel bootstrapping implementation... As it stands, the `remap_the_kernel` function is certainly not safe to call more than once!

It seems like whoever "owns" the memory boot information structure should report its extent, right? One idea I had was to move some or all of `remap_the_kernel` to the frame allocator, which already knows about the kernel and boot info extents... Perhaps that's a safer option?

A final thought: do we even want to identity map this structure? Could we map it right after the kernel, or move it (or the relevant parts of it) onto the stack instead? It seems like some of this depends on the strategy you end up going with for allocation since the frames allocated to the heap will need to avoid clobbering this structure (and will probably need to use this structure to figure out how many frames it has to allocate). Looking forward to that post!

**Comment by phil-opp** [comment]
>The &'static annotation in the AreaFrameAllocator should probably have been a red flag! It seems to me that anything that's marked &' static needs to be mapped and survive for the lifetime of the program otherwise you're lying to the compiler.

An alternative would be to use raw pointers in `AreaFrameAllocators`, but I don't think this would make it safer. My plan was that the multiboot structure remains identity mapped, so `'static` seemed fine. But yeah, it's important to use `'static` carefully (in combination with unsafe code) since it's pretty easy to create an invalid reference such as this one…

>  I'm new to rust, so I'm curious whether you think my code is the best approach to solving the problem. Is it safe to assume that the boot information structure fits in one page (probably not), that the reference doesn't use some sort of magic (like implementing Deref) that invalidates my type cast, etc?

Your code is fine, I would do it the same way :). You can always cast a reference to a raw pointer safely as long as it's not e.g. a [trait object](https://doc.rust-lang.org/book/trait-objects.html). Just rely on the compiler, it complains on invalid casts ([example](http://is.gd/9Lk7mO)).

The multiboot information struct is dynamically sized (see section 3.4 in the specification [PDF](http://nongnu.askapache.com/grub/phcoder/multiboot.pdf)). With the right input, it may not fit into one page. For example, if our kernel ELF file contained an own section for each function, the ELF section tag would become very large. _But_: We have complete control over our kernel, so _our_ multiboot structure should not be bigger than a page. On my machine, `multiboot_end-multiboot_start` is just 1352 bytes. So mapping one page should suffice.

> It seems like whoever "owns" the memory boot information structure should report its extent, right? One idea I had was to move some or all of remap_the_kernel to the frame allocator, which already knows about the kernel and boot info extents... Perhaps that's a safer option?

Well, honestly I'm not quite sure if the function is “safe” at all. What happens if it's called a second time? Maybe we should make it an unsafe function…

Of course we could split it and maybe it's a good idea to do so (e.g. the vga_buffer module takes care of mapping the text buffer, etc.). It was just easier to explain it in the blog post this way. But I would not spend too much time on improving this function since it's only called once. And there will always be some rough edges in such low-level code :).

> A final thought: do we even want to identity map this structure? Could we map it right after the kernel, or move it (or the relevant parts of it) onto the stack instead?

We could map it any virtual address we want. `0xdeadbeaf0000`, `0xcafebabe0000`, or `0xbadc0ded0000`, it's up to you ;). But then we would need to update its internal pointers and it has many pointers… Normally, grub puts it near the end of the kernel and I think that's a good place. And it makes things easy if we keep it there, so identity mapping is the easiest option.

Alternatively we could just extract the needed information about memory areas and leave the rest unmapped. Putting it on the stack will not work for all cases since the memory map is dynamically sized could theoretically contain many memory areas (so how much memory do we reserve on the stack?). But normally, a standard computer has no more than 3 memory areas so we could just use a small fixed size array.

> It seems like some of this depends on the strategy you end up going with for allocation since the frames allocated to the heap will need to avoid clobbering this structure

It's already handled in the [frame allocator](http://os.phil-opp.com/allocating-frames.html#the-allocator). If the frame is used by the multiboot structure, the allocator won't return it. Another reason to keep the identity mapping :).

> Looking forward to that post!

Soon! Unfortunately I'm pretty busy right now but I try to write it as soon as I have some spare time again.

**Comment by mmalone** [comment]
Thanks for the feedback, looks like you've got a good game plan.

I found another (related) issue though. After adding some more code to the project I got a panic in `mapper.rs:map_to` from our assert that `page.is_unused()`. I tracked the panic back to the new code that identity maps the multiboot information structure.

After a bit of debugging I think I figured out what happened, but I'm not sure what the best solution is. It looks like my data (`.bss`) section grew to `0x6008` bytes. All of my sections are page aligned, but our `ALIGN` statements only guarantee that the section _starts_ on a page boundary. The _end_ can be unaligned (i.e., section size is not a multiple of page size). It looks like Grub is noticing the unused space between `.bss` and the next section, and tossing the multiboot information structure in there. Inside remap_the_kernel we identity map the last page of `.bss` as part of our kernel section remapping, then we try to identity map that same page again for the multiboot structure, causing a panic.

I can think of a couple solutions:

1. Only identity map the page containing the multiboot structure if it's not already mapped. There could be some other problems with this approach though:
  1. Could Grub put the structure on a kernel page that doesn't have the correct permissions? I guess all we need is PRESENT, so probably not..?
  2. Could the multiboot structure actually extend past a page boundary if it's tacked at the end of a section like this, even if it's less than a page long? If the next section is aligned to start on the next page I'd imagine not since it would be impossible to fit the structure in the gap. But if the next section were, say, 8K aligned it might be possible (of course we can simply not use such alignments).
2. Tell Grub to page align the multiboot structure... not sure if this is even possible.
3. Tell the linker to make the section _size_ a page multiple in addition to (or maybe just instead of?) page aligning the section _start_. That way Grub can never use a page that's already partially used by some other section since sections don't use partial pages.

For now I've opted for the third approach. My `ld` foo is weak, but adding `. = ALIGN(4K)` to the end of each section appears to force `ld` to end each section on a page boundary (i.e., allocate a multiple of our page size for each section). For example, my `.bss` section in `linker.ld` now looks like this:

    .bss : ALIGN(4K)
    {
        *(.bss*)
        . = ALIGN(4K);
    }

After adding that one line things started working again. To be safe though I've given every section the same treatment, but maybe that's overkill?

**Comment by mmalone** [comment]
By the way `objdump -h build/kernel-x86_64.bin` was enormously helpful in debugging this issue and might be worth mentioning in the post if you discuss this issue at all.

**Comment by phil-opp** [comment]
Oh wow, that's unfortunate… Thanks a lot for the detailed write up!

In my opinion solution 2 would be the best, but I don't think that it's possible.

Solution 1 should work too as long as all sections are 4K aligned since then (1ii) is not possible. (1i) should not be a problem either, since each section is at least PRESENT as you said. This solution feels hacky, but it's easy.

Solution 3 would be my preferred approach, too. It requires some fiddling on the linker script, but I think it's the cleanest solution. Each section is treated already as if its size were a multiple of 4K (e.g. we set the permissions for the whole page). We can even remove the alignment of the section start, as you suggested (the start address is page aligned and each section size is a multiple of 4K, so each section is still page aligned).

> To be safe though I've given every section the same treatment, but maybe that's overkill?

I think it's required since grub could put it in every hole between sections, couldn't it?

-

However, I don't think that an explanation of this issue would fit well into the “Remap the Kernel” post.  The post is pretty long already and we don't need the `FrameAllocator` in it.

I would rather put it in the next post where we create a heap allocator. I think it's interesting enough to debug and discuss it in detail. We could then add a quick note in “Remap the Kernel” that the `FrameAllocator` is broken and that we'll fix it in the next post. Or how would you do it?

**Comment by mmalone** [comment]
Yea as I proceed I'm thinking more and more like #3 is the best solution. At this level (pre-heap-allocator) it's just way easier to reason about various pieces when they are page-aligned and exclusive owners of their pages. I've kept the ALIGN(4K) at the section start too -- probably redundant, but it doesn't seem to hurt anything.

I think it would be fine to go into more detail in the next post, as you suggest. The debugging here was interesting and it serves as a good reminder of how these components interact / gives everyone another chance to think about the linker and how virtual memory works.

I had to go back to the linker script again when I enabled interrupts and retargeted my compiler (per Eric Kidd's instructions). When I did that the .gcc_except_table disappeared and I started getting a .got (global offset table) instead. It's funny, I understand conceptually what both of those things are but I haven't figured out yet why the retargeting / interrupt enabling made one show up and the other disappear! So much infrastructure!

**Comment by phil-opp** [comment]
Another thought: Maybe the other alternative is easier after all:

>Stop using the AreaFrameAllocator and use some other FrameAllocator after the kernel remap

We could just add a new `FrameAllocator` such as the following:

```rust
use core::ops::Range;

struct RangeFrameAllocator {
    free_areas: [Option<Range<Frame>>; 10],
}

impl FrameAllocator for RangeFrameAllocator {
    fn allocate_frame(&mut self) -> Option<Frame> {
        for area_option in &mut self.free_areas {
            if let Some(Range{start: Frame {number: start}, end: Frame {number: end}}) = *area_option {
                if start == end {
                    *area_option = None;
                }
            }
            if let Some(ref mut area) = *area_option {
                let frame = area.start.clone();
                area.start.number += 1;
                return Some(frame);
            }
        }
        None
    }
}
```

It has room for 10 memory areas which should be more that needed for most (all?) systems. We could take the old frame allocator by value in `remap_the_kernel` and return the new one, which we create just before switching tables.

**Comment by mmalone** [comment]
Yea that's what I was thinking at first... sort of what I meant by "copying the relevant parts onto the stack," since those Range's would be Sized and stack allocated (er, I guess maybe they'd be in .data... whatever). I'm sure that wasn't clear.

Is there anything else you'll need from the multiboot structure going forward? The AreaFrameAllocator and BootInfo objects will cause a page fault if you access them after the remap, so if we go this direction we should probably make sure those variables go out of scope once this allocator is created. Rust makes this easy enough, but we'll still have that `multiboot_information_address` hanging around unless we leave `rust_main`. Since either approach adds some complexity it's not clear to me which is better.

Maybe the first thing we should do is get a better sense of what memory areas actually are. Personally, I only have a vague sense of their meaning and purpose: they're just address ranges that the BIOS detects to tell you where memory mapped devices are, right? My understanding is there are only a couple gaps in the <1MB space and one just below 4GB, so there should be a small fixed number of areas... but I'm not sure if that's always true. Anyways, if grub has already gone through the trouble of figuring out how many of these areas exist, and we've already got it mapped into memory, seems like a waste of effort to move it somewhere else unless we want to reclaim some of that memory for something else, or improve the performance of the frame allocator, right?

**Comment by phil-opp** [comment]
> When I did that the .gcc_except_table disappeared and I started getting a .got (global offset table) instead. It's funny, I understand conceptually what both of those things are but I haven't figured out yet why the retargeting / interrupt enabling made one show up and the other disappear!

Neither do I :) Maybe it has something to do with `no-compiler-rt: true`…

> Yea that's what I was thinking at first... sort of what I meant by "copying the relevant parts onto the stack," since those Range's would be Sized and stack allocated (er, I guess maybe they'd be in .data... whatever). I'm sure that wasn't clear.

It was clear, I just thought it would be more complicated. But now that the linking issue came up I'm not sure what's easier.

>Is there anything else you'll need from the multiboot structure going forward?

I'm not sure. But not in the near future…

>if we go this direction we should probably make sure those variables go out of scope once this allocator is created

Good point!

>Maybe the first thing we should do is get a better sense of what memory areas actually are. [...] they're just address ranges that the BIOS detects to tell you where memory mapped devices are, right?

I think so. And there were only 2 or 3 areas on all systems that I tested. But maybe some exotic systems have more (but should we really support such exotic systems?).

> if grub has already gone through the trouble of figuring out how many of these areas exist, and we've already got it mapped into memory, seems like a waste of effort to move it somewhere else

Yeah, and maybe we need some more of its information later. So I think we should pursue the linker solution and keep the multiboot structure mapped for now.

**Comment by phil-opp** [comment]
>  It looks like my data (.bss) section grew to 0x6008 bytes. […] It looks like Grub is noticing the unused space between .bss and the next section, and tossing the multiboot information structure in there.

It tried to reproduce this and grew my `.bss` section to `0x6008` bytes. But GRUB still puts the multiboot info struct behind the kernel. Maybe it depends on the GRUB version…

@mmalone do you have a version that triggers the issue?

**Comment by phil-opp** [comment]
I've spend some time on this issue today and even tried to find an explanation in GRUB's source (but I could not find any). I really like the details of this issue, but I'm not quite sure if they're interesting enough for outsiders. And I don't have the time for a detailed investigation right now, so maybe it's better to add an update to “Remap the Kernel” which fixes the first part of this issue (the missing mapping of the multiboot info).

I don't think that I want to invest much time to explain the second part (grub places the multiboot info between kernel sections… sometimes). Instead, I would propose that we “hide” that issue by using ` . = ALIGN(4K);` from the beginning. A first draft of these changes is in #131.

**Comment by phil-opp** [comment]
Thanks a lot for the great discussion @mmalone! I hope that the solution is ok for you…
