### ISSUE TITLE
Edition-3 Post 2 (booting):  profiles for the non root package will be ignored

### ISSUE THREAD

**Issue by a-usr** [phil-opp/blog_os#1314]
In the post about booting it is suggested create a new workspace member for the kernel by moving the `src` forder and the `cargo.toml` to a new "kernel" folder, before adding said folder into a new `cargo.toml`'s workspace field. However cargo will Ignore the the profiles inside `kernel/cargo.toml`, as suggested by this warning from `cargo check`:
 ```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   [Path]\kernel\Cargo.toml
workspace: [Path]\Cargo.toml
```

**Comment by ajh123** [comment]
Doesn't the post 1 of edition 3 tell you to remove those profiles?

It says:

> We still get the error about a missing `start` language item because the custom target only removed the dependency on the C library.
To remove the dependency on the Rust runtime as well, we can use the `#[no_main]` attribute.

>Before that, we can do a small cleanup.
The `x86_64-unknown-none` target defaults to `panic = "abort"`, so the we can remove the `profile.dev` and `profile.release` tables from our `Cargo.toml` again.

Those profiles are not needed since the post eventually tells you to use the `x86_64-unknown-none` target.

This means you did not follow all the steps in the post so you now have a `kernel/cargo.toml` which doesn't match what the post says.

**Comment by a-usr** [comment]
I swear I read all the posts multiple times and I still missed this. Thanks anyways, closing this for obvious reasons.
