### ISSUE TITLE
bootimage can't be installed

### ISSUE THREAD

**Issue by Nerocraft4** [phil-opp/blog_os#1329]
Hello,

I've tried to install bootimage several times and I can't manage to do it. I'm stuck at the last part of this tutorial (https://os.phil-opp.com/minimal-rust-kernel/) and bootimage just won't install.

I get thousands of errors:

```bash
Some errors have detailed explanations: E0405, E0412, E0425, E0432, E0433, E0463, E0531.
error: could not compile `serde` (lib) due to 6739 previous errors
error: failed to compile `bootimage v0.10.3`, intermediate artifacts can be found at `/tmp/cargo-installud8I1t`.
```

What can I do? I really wanted to follow along the tutorial, but this has stopped me and I can't find anything to solve it.

**Comment by phil-opp** [comment]
Please try running the `cargo install` command from a different directory, e.g. your home directory.

**Comment by Nerocraft4** [comment]
thing is, from there, it tells me the target system (the x86... .json thingy) is not installed. It could be a bug due to the unstable-nightly version, maybe?

**Comment by phil-opp** [comment]
`cargo install` should always build for your host system, not for the custom target. Did you perhaps set the default target in your `$HOME/.cargo/config` instead of a `path/to/your/project/.cargo/config` file? In that case you changed the default target for your whole system, which would explain why the error still happens from your home directory.

**Comment by Nerocraft4** [comment]
thanks! that might be it. I will try again as soon as I can and let you know.

**Comment by phil-opp** [comment]
I'll go ahead and close this because I think this has been answered. Let me know if you still have issues.
