### ISSUE TITLE
PhysicalAddress and VirtualAddress types probably shouldn't be interoperable

### ISSUE THREAD

**Issue by ketsuban** [phil-opp/blog_os#145]
At the moment you define `PhysicalAddress` and `VirtualAddress` as synonyms via the `type` keyword, but this has the sideeffect that either can be passed to functions that take the other since they're both `usize`. It might be worth defining them via the newtype pattern (`struct PhysicalAddress(usize);`) instead.

**Comment by phil-opp** [comment]
Usually I'm a big fan of the newtype pattern. However, I think it leads to unneeded verbosity in this case.

I've implemented the change for testing purposes [here](https://github.com/phil-opp/blog_os/compare/master...033f81df8ffc2984057a20e82ad0a97a89148e2f). We often do calculations or checks on the addresses so that we need to add a `.0` suffix in many places. We also do pass some physical addresses to functions that expect virtual addresses (e.g. for identity mapping). In these cases we need more casting logic with newtypes.

The `PhysicalAddress` and `VirtualAddress` types are private to the `memory` module, so the safety advantages are rather small. But we would need to change the code in many places. We could also need to adjust the corresponding posts, which is somewhat elaborate.

So I'm inclined to keep the `type` synonyms, but I'm happy to discuss it further :).

**Comment by DSMan195276** [comment]
Just to show a different point of view, in my kernel I have two separate types for virtual-addresses and physical-addresses - And even though it's C, I still kept them [incompatible](https://github.com/DSMan195276/protura/blob/master/arch/x86/include/arch/types.h#L41), as Ketsuban suggested, though with a bit different of a technique. I've found this to save me tons of headache, because using the wrong type of address is a fairly common problem in the allocators (And without type checking, it's easy to simply guess the wrong type of address something needs).

It's also fairly simple, as I simply declared my `PhysicalAddress` to be an integer type, and my `VirtualAddress` to be a generic pointer type, thus making them automatically incompatible. These are also more natural types for these things to be - `VirtualAddress`s are generally treated as pointers since they're actually mapped, where-as `PhysicalAddress`s should never be directly dereferenced.

**Comment by phil-opp** [comment]
I agree that different types is the better choice here. We could replace most of the `.0`s with explicit conversion functions and/or implementations of the [Into trait](https://doc.rust-lang.org/nightly/core/convert/trait.Into.html) trait.

**Comment by phil-opp** [comment]
I agree that different types are the better choice here. We could replace most of the `.0`s with explicit conversion functions or implementations of the [Into trait](https://doc.rust-lang.org/nightly/core/convert/trait.Into.html). If I recreated the project, I would probably choose the newtype pattern too. However, my concern is that we would change the code of multiple posts, which could cause some confusion when people already implemented the old code.

So we have 3 options:

1. Leave everything as it is and keep the `type` synonyms. Minimizes breakage and confusion, but it is possible to pass a `VirtualAddress` to a function that expects a `PhysicalAddress`.
2. Update the code and all affected posts to use the newtype pattern. Makes `PhysicalAddress` distinct from `VirtualAddress` and `usize` and solves the problem of option 1. However, it changes the code and the corresponding posts in many places and might confuse people that are halfway through.
3. Refactor the code to use the newtype pattern as part of a future post. For example when we extend the memory module eventually. Alternatively, we could collect “minor” changes like this and create some “Various Safety Improvements” post. This has the advantages of options 1 and 2, and allows us to motivate the change for the readers. However, it would postpone this issue for a probably long time.

I think I like option 3 the most… What do you think?

**Comment by Ketsuban** [comment]
I'm okay with option 3 as well—it'd work thematically with the cleanup of the build system you teased as part of a general tidy-the-code block, if that sounds like a way to go.

**Comment by phil-opp** [comment]
We now use the address types of the `x86_64` crates which are newtypes, so I think we can close this.
