### ISSUE TITLE
Obscure heap allocation issue (Vec w/ odd elements followed by Box-allocation of struct)

### ISSUE THREAD

**Issue by simonlovgren** [phil-opp/blog_os#160]
**I'm part of a group trying to build an OS in Rust as a project in one of our courses and your tutorial series has been a great resource for how to even get started. It has also been a great read, keep up the great work! :)**

We have, however, hit a rather obscure snag with the heap allocator: we get `out of memory` when the heap is still basically unused. We've tracked the issue to the use of the `vec` macro, but **only when allocating**:

- A single `Vec` with an uneven number of elements (`let v = vec!(1,2,3,4,5)`)
- Multiple `Vec` where the total number of elements are uneven

followed by allocation of a struct using `Box::new()`. This is possibly due to some sort of alignment issue with odd-element-vectors. It seems, however, to not cause an issue if the `Vec` contains a small enough number of elements (for us 5 or more elements has triggered this issue). Oddly enough allocating a single value- or array using `Box` works fine, as is using `String`.

For example, this works fine:
```rust
struct MyStruct {
  val: usize
}

let v = vec![1,2,3,4,5,6,7,8];

let a = Box::new(MyStruct{val: 123});
```

but these examples somehow trip up the allocator:
```rust
struct MyStruct {
  val: usize
}

let v = vec![1,2,3,4,5,6,7];

let a = Box::new(MyStruct{val: 123});
```

```rust
struct MyStruct {
  val: usize
}

let v1 = vec![1,2,3,4,5,6,7,8];
let v2 = vec![1,2,3,4,5,6,7];

let a = Box::new(MyStruct{val: 123});
```

***
### Note on the tutorial-page
I'll also point out that at the end of [Kernel Heap/A better allocator/Implementation](http://os.phil-opp.com/kernel-heap.html#implementation-1), should it not be *hole_list_allocator* instead of *linked_list_allocator*? Namely this section:
```patch
in memory::init in src/memory/mod.rs:

-use bump_allocator::{HEAP_START, HEAP_SIZE};
+use linked_list_allocator::{HEAP_START, HEAP_SIZE};
```

Thanks again!

**Comment by simonlovgren** [comment]
I forgot to mention that we do cross-compile rust nightly as a custom-target with no-redzone and applying a patch removing floating point operations within the kernel as per this guide: [Bare Metal Rust 2: Retarget your compiler so interrupts are not evil](http://www.randomhacks.net/2015/11/11/bare-metal-rust-custom-target-kernel-space/) using [this patch](https://github.com/thepowersgang/rust-barebones-kernel/blob/master/libcore_nofp.patch) and parts of [this Makefile](https://github.com/thepowersgang/rust-barebones-kernel/blob/master/Kernel/Makefile).

We currently compile *libcore* (patched), *liballoc*, *librustc_unicode* and *libcollections* as our custom target.

**Comment by simonlovgren** [comment]
I just verified the same issue occurring using the [Kernel Heap](https://github.com/phil-opp/blog_os/tree/592dcee93e8c04f4b5200bd71c4ba0f2821ff231) release of the blog_os using the regular `multirust override nightly` target.

**Comment by phil-opp** [comment]
Thanks a lot for reporting and for the comprehensive description!

> Note on the tutorial-page

Good catch! I fixed it in #161.

> these examples somehow trip up the allocator

Yeah, I can reproduce the `out of memory` errors. Not sure what's happening though…

**Comment by phil-opp** [comment]
Ok, I found the problem. You're right, it is an alignment issue.

The default type for integer literals is `i32`, so the vector has align 4. The `MyStruct` type is an `usize` and has align 8. When you create a vector through the `vec!` macro, the compiler reserves excactly the needed memory (with align 4). Thus, the allocation end is 8-byte aligned for an even sized vector and 4-byte aligned for an uneven sized vector.

So we have a hole (block of free memory) that starts at a 4-byte aligned address. Now we try to allocate a `MyStruct` type, which requires align 8. The linked_list_allocator crate [tries to split the hole](https://github.com/phil-opp/linked-list-allocator/blob/fcb9b61276b5e8dbddb078027bfd1f5bf869f2a5/src/hole.rs#L134-137) to satisfy the alignment, but it fails since we can't create a 4 byte hole (too small to store size+pointer). Then the crate continues with the next hole. However, it was the last hole in our case and thus it fails with `out of memory`.

To fix this, we need to split the hole into (4+16=20 bytes, rest) instead of (4 bytes, rest), when the required padding would lead to a too small hole. I'll try to fix it in the next few days.

Thanks again for reporting!

**Comment by phil-opp** [comment]
Update: I've added a (still failing) [test case](https://github.com/phil-opp/linked-list-allocator/commit/7bf28e8e7cf5b7d5f659d283f50193783a93fd6c) to the linked-list-allocator crate.
