### ISSUE TITLE
Avoid data race on output buffer

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#167]
See [taricorp's comment](https://www.reddit.com/r/rust/comments/4lfx0f/writing_an_os_in_rust_catching_cpu_exceptions/d3n2w9i) on /r/rust.

**Comment by tari** [comment]
I believe this does not qualify as a data race, because there is no reading happening. That's consistent with LLVM's definition, but it's not clear what Rust guarantees in this case. If it simply inherits LLVM's model (which is probably what happens in practice but may not be an intended part of the design contract), volatile stores should be sufficient to ensure the memory writes actually happen.

Excerpt from some of my own code (for clearing VGA memory) where I've tried to ensure correctness while permitting maximal optimization:
```rust
// This is vectorizable but volatile_set_memory only works on bytes
// and we need to write a 16-bit pattern (and doing a sequence of
// volatile stores can't be vectorized by the compiler). Thus we do
// non-volatile stores and force the compiler to commit them.
// This is not quite ideal since we'd like to permit certain operations
// to be elided or reordered (cursor location), but no compiler is
// really capable of doing fences specific to a set of memory locations.
for i in 0..VGA_SIZE {
    // Nice blue, space character
    *VGA_BASE.offset(i) = 0x1F20;
}
intrinsics::atomic_singlethreadfence();
```

**Comment by phil-opp** [comment]
A thought a bit more about this and noticed that there _is_ a read happening: Whenever we shift lines up (i.e. newline), we read a line and write it to the line above… So we get a data race when two threads print simultaneously.

Fortunately, we don't have threads yet. But we need to find a better solution for the future.

**Comment by phil-opp** [comment]
Closing, since this doesn't affect the second edition.
