### ISSUE TITLE
General Protection Fault when running on hardware

### ISSUE THREAD

**Issue by nxnfufunezn** [phil-opp/blog_os#179]
I am getting Exception number 0xD when running on hardware.
This also happens on enabling KVM using `-enable-kvm` on qemu.
What could be the cause of this ?

**Comment by phil-opp** [comment]
Thanks for reporting! I can reproduce it with `-enable-kvm` (I didn't try it on real hardware yet).

It seems like it was introduced with the [Catching Exceptions](http://os.phil-opp.com/catching-exceptions.html) post. But I don't know what's happening yet.

**Comment by nxnfufunezn** [comment]
This also happens on key press.
This is wrt my branch which has keyboard support..
https://github.com/nxnfufunezn/RstyOS/tree/some-more-exceptions

**Comment by phil-opp** [comment]
Ok, here is what I found so far: It's caused by a `movaps` instruction with an unaligned stack pointer (must be 16byte aligned but is only 8byte aligned). It occurs inside the `write_fmt` call in the `print_error` function, when the page fault handler is called the first time.

However, the stack pointer is correctly aligned when the page fault handler is called (it seems like the CPU does this automatically before pushing anything).

**Comment by nxnfufunezn** [comment]
How did you figure that out..? Maybe this will save me hours next time...

**Comment by phil-opp** [comment]
I first inserted random `loop{}` statements to narrow it down. Thus I found out that the page fault handler is called correctly. It's just the `print_error` call that causes the general protection fault. QEMU interrupt debugging doesn't seem to work with `-enable-kvm` and normal GDB breakpoints does not work either. But you can use GDB with hardware breakpoints, e.g. `hb vga_buffer.rs:41`.

So I added a breakpoint on `print_error` and stepped through it. It fails on `writer.write_fmt(fmt);`. Next I tried to `disassemle` the code in GDB and stepped through it through `si`, which steps a single assembly instruction. The fault occured on a `movaps` instruction, so I checked the [docs](http://x86.renejeschke.de/html/file_module_x86_id_180.html). It throws a general protection fault “if a memory operand is not aligned on a 16-byte boundary”. So I checked `rsp` just before the `movaps` through `info registers rsp` and indeed, it was not correctly aligned.

But I still don't know what causes the wrong alignment.

**Comment by nxnfufunezn** [comment]
thanks.. :smile:

**Comment by phil-opp** [comment]
Inserting `unsafe {asm!("push rax" :::: "intel");}` at the beginning of the page fault handler fixes it. But I don't understand why :D.

**Comment by nxnfufunezn** [comment]
I am using naked functions for interrupts and so I am doing just that https://github.com/nxnfufunezn/RstyOS/blob/some-more-exceptions/src/interrupts/idt.rs#L27

still faults...

**Comment by nxnfufunezn** [comment]
but when I removed `push rax` and `pop rax` it works!

**Comment by phil-opp** [comment]
Mystery solved, thanks to @Tari and @Ketsuban on #rust-osdev.

Citing @Tari:

> C ABI (assuming system V) does require that rsp be 8 bytes above a 16-byte alignment

And @Ketsuban reminded me that the CPU pushes an error code for some faults (including page faults).

So the following thing happens:

1. The page fault occurs.
2. The CPU aligns rsp automatically to 16 bytes.
3. The CPU pushes RIP, RSP, and EFLAGS (not sure in which order). Now the stack pointer has the required alignment (8 bytes above a 16-byte alignment).
4. The CPU pushes the error code. Now the stack pointer is 16-byte aligned again.
5. We execute our exception handler with the invalid stack pointer.

So it works fine for exceptions without error code but requires a stack adjustment for other handler functions. It seems like I need to update the _Catching Exceptions_ post considerably :).

Thanks again for reporting this!

**Comment by nxnfufunezn** [comment]
Mystery solved.. :confetti_ball: :tada: 
Thanks..

**Comment by nxnfufunezn** [comment]
In my case was this because of red zone ?

**Comment by phil-opp** [comment]
I don't think that the red zone causes this. The red zone is a software convention that allows programs to use some bytes below the stack pointer. It does not change any stack alignment.

IntermezzOS doesn't have this GP fault because the custom target disables SSE. Thus, the `movaps` instruction, which requires the stack alignment, is no longer available and the compiler generates different code. However, the compiler still assumes that the handler function is called with a correctly aligned stack pointer. It just has no way to exploit this requirement.

So disabling SSE might be a workaround, but it's not a clean solution. A better solution is to write custom assembly stubs for exceptions with and without error code and align the stack correctly in them.

**Comment by steveklabnik** [comment]
> A better solution is to write custom assembly stubs for exceptions with and without error code and align the stack correctly in them.

I am planning on doing this, but haven't gotten to it yet.

**Comment by phil-opp** [comment]
Closing, because #187 somehow fixes it. The upcoming post will introduce assembly stubs and correct error code treatment.
