### ISSUE TITLE
No Linker Errors

### ISSUE THREAD

**Issue by skriptble** [phil-opp/blog_os#205]
I'm currently working through the "set up rust" blog post and I noticed that when I get to the fixing linker errors that I don't have any linker errors. I do get the errors starting from the --gc-sections section and forward. I also get an "unused variable: `x`" warning.

rust version: rustc 1.12.0-nightly (1deb02ea6 2016-08-12)

**Comment by phil-opp** [comment]
Thanks for reporting this! I just tried again it and I don't get the `memcpy` linker error either.

So the compiler no longer emits `memcpy` calls for the following code:

```rust
let x = ["Hello", " ", "World", "!"];
```

However, we still need `memcpy` and `rlibc` for future code (the master branch doesn't compile without `extern crate rlibc`). So the best solution would be to find some short example code that triggers the `memcpy` linker error again.

**Comment by phil-opp** [comment]
The only example I could find is the [format_args!](https://doc.rust-lang.org/nightly/std/fmt/#format_args) macro:

```rust
format_args!("{}", "Hello");
```

```
target/x86_64-unknown-linux-gnu/debug/libblog_os.a(core-c8005792.0.o): In function `core::fmt::Formatter::pad_integral::hb1b426300c793414':
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12pad_integral17hb1b426300c793414E+0x15d): undefined reference to `memset'
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12pad_integral17hb1b426300c793414E+0x1fe): undefined reference to `memset'
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12pad_integral17hb1b426300c793414E+0x2d8): undefined reference to `memset'
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12pad_integral17hb1b426300c793414E+0x3b5): undefined reference to `memset'
core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12pad_integral17hb1b426300c793414E+0x4fb): undefined reference to `memset'
target/x86_64-unknown-linux-gnu/debug/libblog_os.a(core-c8005792.0.o):core.cgu-0.rs:(.text._ZN4core3fmt9Formatter12pad_integral17hb1b426300c793414E+0x5fa): more undefined references to `memset' follow
Makefile:43: recipe for target 'build/kernel-x86_64.bin' failed
make: *** [build/kernel-x86_64.bin] Error 1
```

It needs `memset` instead of `memcpy`, but the solution is the same (`rlibc`). However, it's a rather obscure example and we would need to explain the `format_args!` macro.

Does anyone have a better example that triggers a `memcpy`/`memset` linker error?

**Comment by yjerem** [comment]
Here are a few examples I came up with. First, wrapping the array inside another structure (kind of ugly):

```rust
let x = [["Hello", " ", "World", "!"]];
```

```rust
let x = Some(["Hello", " ", "World", "!"]);
```

```rust
let x = (["Hello", " ", "World"], "!");
```

`assert_eq!` seems to use `memset`, so you could replace the example with something like:

```rust
assert_eq!(2 + 2, 4);
```

Or just trigger a `memcpy` very straight-forwardly:

```rust
let x = ["Hello", " ", "World", "!"];
let y = x;
```

```rust
let x = ["Hello", " ", "World", "!"].clone();
```

**Comment by phil-opp** [comment]
Wow! Thanks so much, @yjerem! These are great!

I really like `assert_eq!(2 + 2, 4);`, since it's very simple and doesn't require an array. However, it also goes through the `fmt` machinery and thus outputs the same cryptic error message as the `format_args!` example.

In contrast, the wrapped array examples have the nicest error message (only a single `memcpy` reference right in  `rust_main`):

```
target/x86_64-unknown-linux-gnu/debug/libblog_os.a(blog_os.0.o): In function `blog_os::rust_main':
…/blog_os/src/lib.rs:19: undefined reference to `memcpy'
```
However, I agree that these examples are a bit cumbersome.

So I think I like the last examples most. They are still pretty simple and give good error messages, too:

```
target/x86_64-unknown-linux-gnu/debug/libblog_os.a(blog_os.0.o): In function `blog_os::rust_main':
…/blog_os/src/lib.rs:20: undefined reference to `memcpy'
…/blog_os/src/lib.rs:20: undefined reference to `memcpy'
```
I think I prefer the `let y = x` variant, since it seems a bit simpler than the `clone` variant. And it even works with a smaller array:

```rust
let x = ["Hello", "World", "!"];
let y = x;
```

Do you want to send a PR for this (so that you get the credit)?
