### ISSUE TITLE
Suggestion: Cross complie with xargo

### ISSUE THREAD

**Issue by 4e554c4c** [phil-opp/blog_os#215]
In the blog is a 'Cross Compiling: Libcore' post which describes compiling libcore to `x86_64-unknown-linux-gnu' for the os to compile. This is tedious, and the suggested "easy method" of using cargo requires changing _every_ crate that uses core. My suggestion is to use [xargo](https://github.com/japaric/xargo) to cross compile instead.

The main pros of using xargo in my opinion are as follows
+ It's easy: All I had to do to create cross compiling in my kernel was change `target` in the makefile to 'x86_64-unknown-none-gnu', replace all instances of cargo to xargo, and leave a [x86_64-unknown-none-gnu.json](https://gist.github.com/4e554c4c/1c3839545631308b49faaa2e5b088774) file in the project root.
+ It is scaleable: The llvm target file allows for easy later changes, such as the disabling of sse and hard floats that I did in mine.
+ Installing is not difficult: One can compile xargo on their machine with `cargo install xargo` if they are running a nightly compiler

However, there may be several cons as well
+ Xargo means another requirement for someone to run blog_os. Every person who would compile blog_os from the point this was imlemented onward would have to have to have xargo on their computer.
 + A solution to this would be to put it in the additional resources section, however this would be incredibly difficult with something as integral to the project as a build tool. Every post would have to consider both the xargo and cargo methods of compilation which defeats the purpose
+ It could create a split in the userbase: There may be people who have been folowing the blog for some time and use the traditional method of compilation. There may be an exception post which assumes the kernel compiled with "disable-redzone" which would not work on user's existing kernels.
+ It would create another reliability on unstable software, something else that can break, and something else to support. 

I can create a pull request to implement this, however I think that there should be a conversation for it first, especially because of the different levels that xargo can be used in the project.

**Comment by phil-opp** [comment]
Oh, I totally forgot about the “Cross Compiling: Libcore” post… It's completely outdated and there are much better solutions now. Thanks for the hint and the detailed write-up!

I'm currently writing on a new blog post about returning from exceptions. In it, we will switch to a custom target with red zone and sse disabled. And we will indeed switch to xargo then. Of course it has some disadvantages (most notably: another requirement with its own [dependencies](https://github.com/japaric/xargo#dependencies))), but there aren't any good alternatives.

So we will switch to xargo in the upcoming post. However, I don't think that we should use it in the “Cross Compiling: Libcore” post because it's only intended for custom targets. For official targets such as `x86_64-unknown-linux-gnu`, there is an alternative (better?) solution: `rustup target add x86_64-unknown-linux-gnu`. This approach has some advantages over `xargo`:

- we all build for the same target
- no complicated target json file before it's absolutely needed
- no need to recompile the sysroot as we can just download the official prebuilt copy
- no additional (probably unstable) dependency

Of course it requires [rustup](https://rustup.rs/), but I think it's the de facto standard for managing nightly rust versions.

**Comment by 4e554c4c** [comment]
That sounds great! I'll close the issue if you are going to do this. I followed the 'Retarget your compiler so interrupts are not evil' instructions from Eric Kidd's "Bare Metal Rust" series which inevitably let to xargo with sse and redzone disabled as well.

I would like to eventually switch to the userspace in my kernel. If I allow it a redzone, do I have to change the interrupt code to allow for one? I'm just thinking that not supporting a redzone in interrupt handlers might cause errors later on. I suppose this might not even matter for exceptions, because they push a stack frame that would destroy part of the redzone anyway.

Also I agree that rustup is a better solution. It is also not an alternitive to xargo, because xargo explicitly states that it cannot be used on "official rust targets".

**Comment by phil-opp** [comment]
For each interrupt/exception, the CPU pushes various registers (`rsp`, `rip`, etc). We cannot prevent this because it occurs _before_ any handler function is called. This already overwrites the red zone. So we _can't_ support the red zone in interrupt/exception handlers.

However, we still can allow a red zone for userspace programs. The trick is to have a seperate kernel level stack for each userspace thread. Then we can program in the IDT that the CPU should always switch to the kernel level stack when an interrupt/exception occurs while the CPU executes userspace code (ring 3). This switch occurs before any values are pushed, so we leave the userspace stack completely unmodified.

**Comment by phil-opp** [comment]
Reopening so that I won't forget this :).
