### ISSUE TITLE
Recursive mapping question

### ISSUE THREAD

**Issue by ghost** [phil-opp/blog_os#295]
in the blog you selected P4 slot 511 for the recursive mapping, but on most kernels this slot is used for kernel higher half mapping (because of the performance, this address enables gcc to use -mcmodel=kernel), so if i selected slot 510, can i still follow the tutorial [](http://os.phil-opp.com/modifying-page-tables.html) ? of course with `0xff80000000000000` instead of `0xfffffffffffff000`, if not how can i do it ?

**Comment by phil-opp** [comment]
Sure you can! You just need to modify the address calculation. For example, to access the P4 table itself:

```
with slot 511: 0o177777_777_777_777_777_0000
with slot 510: 0o177777_776_776_776_776_0000
```

To access the P3 table with P4 index `XXX`:

```
with slot 511: 0o177777_777_777_777_XXX_0000
with slot 510: 0o177777_776_776_776_XXX_0000
```

I use octal notation here, since it makes it easier to separate the translation steps. Note that the sign extension (the `0o177777` in the beginning) is still required.

In the page tables post we use a formula to calculate the address of the next level table (`next_table_address = (table_address << 9) | (index << 12)`). This formula only works with index 511, so you have to find an alternative way here.

**Comment by 4e554c4c** [comment]
@phil-opp, the address of the next table can be computed by `next_table_address = (0xffff << 48) | (table_address << 9) | (index << 12)`

**Comment by hackereg35** [comment]
@phil-opp thank you for correcting me about the address, and @4e554c4c this formula does not work, plus shifting by 48, give me gcc warning `left shift count >= width of type`

**Comment by 4e554c4c** [comment]
I'm not quite sure what you want to do, the expression I used works fine in Rust. Perhaps you are not using a 64bit type?

**Comment by hackereg35** [comment]
@4e554c4c i use uint64_t which is 64bit, and beside this warning it does not work i get page fault trying to access the returned table address

**Comment by 4e554c4c** [comment]
@hackereg35, perhaps try `(0xffffUL << 48) | (table_address << 9) | (index << 12)`? I'm not familiar with gcc internals but it seems like you need to either do that or use a 64bit literal e.g. `0xffff_0000_0000_0000`. If you're dereferencing a non-canonical address (like what would happen if `next_table_address` was incorrect) you'll get a GPF, not a page fault so you probably just haven't set up your page table correctly. Remember, you have to set up the recursive mapping in your assembly boot file as well as in Rust (or I suppose C in this case).

**Comment by phil-opp** [comment]
Closing as stale. Also, this seems to be answered.
