### ISSUE TITLE
Wrong link at bottom

### ISSUE THREAD

**Issue by bjorn3** [phil-opp/blog_os#298]
Handling Exceptions has a link to Double Faults at the bottom at the location of the previous post link.

Double Faults has links to Kernel Heap and Handling Exceptions.

Handling Exceptions and Double Faults are in the wrong chronological order.

**Comment by phil-opp** [comment]
Thanks for reporting!

We're currently using the release date to order posts, which does not work anymore since “Handling Exceptions” was released after “Double Faults”. Not sure how to fix this easily, maybe someone else has an idea (we're using [hugo](https://gohugo.io/) for static site generation)?

**Comment by gil0mendes** [comment]
I've been looking into this yesterday, but hugo doesn't seem to provide other ways to get the prev or next link. The `.PrevInSection` and `.NextInSection` only supports the date field. :/

**Comment by phil-opp** [comment]
One possible solution I can think of is to add our own `published` field to all posts (and to use it for displaying, in RSS, etc.) and to use dummy values for the `date` field, that represent the desired ordering. For example:

post | date | published
--|--|--
Kernel Heap | 0008-00-00 | 2016-04-11
Handling Exceptions | 0009-00-00 | 2017-03-26
Double Faults | 0010-00-00 | 2017-01-02

**Comment by gil0mendes** [comment]
That is a clever approach to the problem. I don't know how easily is to implement that in hugo, since that is the first time that I'm using it.
