### ISSUE TITLE
private traits

### ISSUE THREAD

**Issue by swarajd** [phil-opp/blog_os#352]
I'm on this chapter:

and I'm running into this error: 
![image](https://user-images.githubusercontent.com/1250084/30044150-9d005e06-91c9-11e7-92c2-048a5adca35c.png)

it's coupled with this warning

![image](https://user-images.githubusercontent.com/1250084/30044160-ab13e47c-91c9-11e7-9b49-d77137340952.png)

One note is that the `#[allow(private_in_public)]` should be set. However, I don't know where to put this in the context of these errors.

**Comment by phil-opp** [comment]
Thanks for reporting and sorry for the delay!

The problem is that the `HierachicalLevel` trait is private in your code. It should be public (i.e. `put trait HierarchicalLevel {…}`), because it is used in as part of the public function. The `#[allow(private_in_public)]` attribute was a way to turn this warning off, but this is no longer possible.

So the solution is to add a `pub` to the trait definition.
