### ISSUE TITLE
Use links to new Rust book instead of old

### ISSUE THREAD

**Issue by Mackiovello** [phil-opp/blog_os#445]
There are several places where there are links to the first edition of the Rust book. These links should probably be updated to point to the new Rust book. See for example the links in this section: https://os.phil-opp.com/vga-text-mode/#a-println-macro

I could take care of this if you agree that it should be done

**Comment by phil-opp** [comment]
Hi, thanks for creating this issue and offering your help!

I tried to update all links that point to a "There is a new edition of the book and this is an old link." site when creating the second edition, but a few seem to slipped through. I'm happy to merge PRs that update them.

However, there are a few links that deliberately point to the first edition of the Rust book, because the topic is no longer explained in the second edition (these should point to the first edition directly, not to the "There is a new edition of the book and this is an old link." landing page).

**Comment by Mackiovello** [comment]
I think this can be closed now
