### ISSUE TITLE
Post VGA Text Mode Enters Bootloop

### ISSUE THREAD

**Issue by donald-pinckney** [phil-opp/blog_os#456]
As far as I can tell, the code from VGA Text Mode causes QEMU to enter a boot loop for me. Here is my Rust / system info:
```
active toolchain
----------------

nightly-x86_64-apple-darwin (overridden by '[PATH]/rust-toolchain')
rustc 1.29.0-nightly (e06c87544 2018-07-06)
```

Specifically, using the formatting macros seems to cause it to boot loop. The seems to be caused by the formatting that Rust is doing internally, since all the actual VGA stuff works fine on its own.

One partial fix I have is adding `rlibc` as a dependency, and adding `extern crate rlibc;` to `src/main.rs`. Then I can print format strings, but *not* format strings with floats. Something like `println!("Hello {}, {}", 45, 1.0/3.0);` still boot loops.

**Comment by donald-pinckney** [comment]
On further inspection, this was all because I forgot 
```json
"features": "-mmx,-sse,+soft-float"
```
in my target JSON file! Closing this, sorry for the churn.

**Comment by phil-opp** [comment]
@donald-pinckney No worries, thanks for the update! In case you're wondering what's happening without this line:

- The compiler thinks that the target architecture supports SSE instructions, but we don't enable them in the hardware for our kernel (because it would significantly increase context switch times).
- When using the formatting macros, the compiler sees optimization potential by using SSE instructions (e.g. for performing an operation on multiple string bytes at the same time).
- The hardware tries to execute the SSE instruction, but since SSE is not enabled a CPU exception occurs. We did not define an exception handler, so a so called triple fault occurs and the machine resets itself. See the “CPU exceptions” post for more details.
