### ISSUE TITLE
Some questions about the blog

### ISSUE THREAD

**Issue by yjhmelody** [phil-opp/blog_os#459]
Thank for your blog about making a OS.
I learned something new about OS and Rust lang.

How much content does this blog plan to contain, such as process management, and the file system will be in the plan?

**Comment by phil-opp** [comment]
Hi @yjhmelody, glad to hear that! I don't really have long term plans for the blog. For the short term, I plan to dive into hardware interrupts (including timer interrupts) and then use the timers to create and schedule multiple threads. After that, I plan to port the memory management chapter of the first edition, which explains how to create and organize page tables and distinct address spaces. This will allow us to allocate proper stacks for our threads and also to create processes with isolated address spaces. This might be a good time to do some posts about scheduling. File systems are not part of my "short term" plan, because there are other things that I find more interesting (e.g. entering userspace, inter process communication, etc).

I hope this answers your question. Note that this is just a vague plan that might change completely. Also, writing these posts takes a long time, so don't expect anything in the near future.

**Comment by yjhmelody** [comment]
Thank for your reply.
