### ISSUE TITLE
Remove remaining uses of #[macro_use]

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#499]
Continuing the discussion from https://github.com/phil-opp/blog_os/issues/405#issuecomment-437739645.

To summarize the issue: We're still using the `#[macro_use]` attribute for importing internal macros (`print`/`println`, `serial_print`/`serial_println`). The other macro imports are already replaced with normal use statements, which is the default since later Rust versions.

It seems however that local macros are not supported by the new import logic, only extern macros. I don't know the reason for this, but it seems like a strange decision. Interestingly, exported macros behave completely different: They are part of the root namespace and can be imported with normal use statements. This means that we have to do `use crate::println` and not `use crate::vga_buffer::println`, which I find very confusing (especially the "can't find …" error message).

Another issue is that we always need to import both `print` and `println`, because `println` uses `print` internally. I don't know if there is a way to avoid this.

Finally, I was not able to find any documentation that describes the new macro import system and its limitations.

cc @kballard

**Comment by kballard** [comment]
I don't know the reason either. My best guess is that you can't declare a macro to be `pub` and therefore the only way to have a non-exported macro be visible outside of its local module is by putting `#[macro_use]` on the module. More generally, the RFC that defined this new behavior is primarily concerned about macros 2.0, so I guess they wanted to keep macros 1.1 largely unchanged.

Regarding the need to import `print` as well, the solution there is to change the `println!` definition to use `$crate::print!()` instead of a bare `print!()`. This looks like

```rust
#[macro_export]
macro_rules! println {
    () => (print!("\n"));
    ($fmt:expr) => ($crate::print!(concat!($fmt, "\n")));
    ($fmt:expr, $($arg:tt)*) => ($crate::print!(concat!($fmt, "\n"), $($arg)*));
}
```

**Comment by bjorn3** [comment]
You can use:

```rust
pub macro println {
    () => ($crate::print!("\n")),
    ($fmt:expr) => ($crate::print!(concat!($fmt, "\n"))),
    ($fmt:expr, $($arg:tt)*) => ($crate::print!(concat!($fmt, "\n"), $($arg)*)),
}
```

You may have to remove the `$crate::`.

**Comment by phil-opp** [comment]
Thanks! See #501
