### ISSUE TITLE
Leverage git history to simultaneously maintain working examples for each post

### ISSUE THREAD

**Issue by Ericson2314** [phil-opp/blog_os#520]
Have you considered having a branch for the code for each post in the series? Each branch woudl containing all the code in the code snippets together in a working a working example, but nothing additional from later installments to distract. Crucially, when one post builds on a previous one, it would be a fork of it. That means if something in Rust unstable improves affecting multiple blog posts, you can update just manually update the first blog post effected by it, and then merge into later posts' branches to propagate the change to the rest. `master`, as the grand culmination of all the blog posts, would have most of the other branches merged into it.

This first occurred to me years ago, but now that you are embarking on a second edition, I hope might be more pertinent.

**Comment by phil-opp** [comment]
I did something similar with the first edition. There were (and still are) `post_X` tags with the source code for each post. For example https://github.com/phil-opp/blog_os/tree/post_4. The history of these tags is independent of the master branch and each change that updated a post's code was cherry-picked to the corresponding tag. On each change, I rebased the tags on top of each other to keep them up to date. I used tags instead of branches because the posts are quite similar to releases, which are often marken with git tags. Also, we don't clutter the branch list this way.

I think it's worth to keep the master branch separate to avoid impacting the normal work flow. This way, changes that affect multiple posts are still possible with a single commit/pull request. Also, we can keep the blog posts and the configuration for the static site generator separate, and only need to backport code changes.

I wanted to add such tags to the second edition too, I just haven't found the time for it yet. What do you think about this approach?

**Comment by Ericson2314** [comment]
So first of all, anything that involves rebasing non-upstream branches means any sort of collaboration is hard. It's possible with `rebase foo --onto bar` to rebase on your rebase, but it requires a lot of care. I once had a project where I did lots of rebasing (sort of bisecting bugs; the process was a port from Windows to Linux), and no one else could do very much.

Here's a diagram of what I was proposing.
```
  Post 1 original           Post 1 revision
       v                         v
       o-------------------------o <== post 1
        \                         \
        |\                        |\
        | \ Post 2 original       | \ Post 2 updated from Post 1
        |  \ v                    |  \ v
        |   o-------------------------o <== post 2
        |    \                    |    \
        |     \                   |     \
        |      \                  |      \
        |       \                 |       \
        |        \                |        \
        |         \               |         \
        |          \              |          \
- - ---o------------o-------------o-----------o <= master
        ^           ^             ^           ^
     Merge 1     Merge 2     Merge 1 rev     Merge 2 rev
```
The main idea is that there is 2 "dimensions" which the repo can change---more posts or revised posts. I'm not sure anything that doesn't involve these "cascading" merges can handle that without force-pushes.

> I think it's worth to keep the master branch separate to avoid impacting the normal work flow.

Yeah that's fine! The other branches get merged back into master when *they* change to keep master up to date, but master itself can be changed in all the same ways. You can see how the post 1 branch is made from an "orphan" commit, indicating that it's fine if this branch strategy is taken after the fact with existing posts too.

> Also, we can keep the blog posts and the configuration for the static site generator separate, and only need to backport code changes.

Yeah I don't think this should be done for anything *but* the code. Only the code builds off each other in terms of each *revising* the last. The post texts are fresh/independent so there's nothing from old posts to merge into new posts. (Well, maybe high conceptual changes, but nothing git could assist with.)

**Comment by phil-opp** [comment]
I agree that rebasing makes things harder. It was always difficult to get it right with the `post_` tags.

Thanks for the diagram, it is really useful. So even though it is still possible to push code changes directly to master, it would be better if we filed them against the respective post branch and then merge them iteratively?

One thing that I'm not sure about is the noise introduced by the merge commits. A change in an early post would result in N merge commits in master (one for each post branch). Wouldn't it suffice to only merge the latest post branch into master?

**Comment by phil-opp** [comment]
Another issue I can see is that a commit is no longer able to update a post and the code in a single PR, e.g. when updating a dependency version. Maybe it's better to keep the master branch completely separate from the post branches and manually check whether the code of the last post matches with the master code.

**Comment by Ericson2314** [comment]
>  it is no longer possible to update a post and the code in a single PR

Actually this gives me an idea. The post 1 branch can contain the post 1 text, and the post 2 branch can contain the post 1 and post 2 texts (even though it only contains the post 2 code). That will allow code changes to bubble up without creating spurious merge conflics in text.

> Wouldn't it suffice to only merge the latest post branch into master?

So post `n`'s branch is only merged into post `m`'s branch only when `m` directly builds on `n` (e.g. the user is suppose to modify the code they already wrote.) A post with no predecessor post would be another orphan commit, just like post 1, and a post with no successor is merged just into master.

This means we could have any tree (or even DAG if a post has two predecessors), not just a linear chain. Other graphs have shorter longest paths, so less than N merges.

**Comment by Ericson2314** [comment]
> But this is always the case for the blog, isn't it?

My bad, I thought there were a few clean breaks.

> Also, these merges should be automated as far as possible since doing 10+ manual merges on every change to an early post isn't practical.

I'd be happy to write a little script. It could maybe be turned into some sort of post push hook, but I'm not sure the details on those things.

> I don't think this is a good idea....

That's fine! The text-in-branches idea is a purely optional variant.

> Overall I'm in favor of a more practical variant...

Are you saying you wouldn't merge the `z-post_*` branches into `master`, or just that code development starts on `master`?

If just the latter, I actually think that's the same thing! My idea really when fully distilled down is just the existence of the `z-post_*` branches and the invariant that:
```markdown
post `n` builds on post `m` ⇒ `z-post_n` ⊃ `z-post_m`
```
Whether you develop on master first or the earliest relevant `z_post_*` branch first is immaterial as long as once the merges are done.

If the former, what if you just merge the last post (whatever it may be) into master? I.E.:
```
  Post 1 original           Post 1 revision
       v                         v
       o-------------------------o <== post 1
        \                         \
        |\                        ?\
        | \ Post 2 original       ? \ Post 2 updated from Post 1
        |  \ v                    ?  \ v
        |   o-------------------------o <== post 2
        |    \                    ?    \
        |     \                   ?     \
        |      \                  ?      \       ???? -- removed merge
        |       \                 ?       \
        |        \                ?        \
        |         \               ?         \
        |          \              ?          \
- - ---o------------o-------------?-----------o <= master
        ^           ^                         ^
     Merge 1     Merge 2                     Merge 2 rev
```
That should still leave master in the same state as the original.

Unless I'm missing something master, since it contains all the features, sort of corresponds to the last post, or last post + potential next posts. So the last post -> master merge should be fairly easy, vs the master->first post backport having to "undo" all the intermediate posts. Of course some changes make most sense in the context of the fully released "blog OS", so developing on `master` first is just the right thing to do. But other things, like Rust gaining a new feature for freestanding dev in general, apply to all posts and master equally, I'd think it just easier to skip the backport, start with the first relevant post, and let the merges do all the work.

All that said, whether or not to merge all the posts or last post into master is something that can easily be started or stopped at any time, so it's not important to decide up front :).

[FWIW, my skin in this really is the that latter sort of case, I really like your blog posts, and I'd love to offer PRs showing how to leverage proposals of mine like `extern existential type` or stdlib-aware Cargo if/when they are accepted. Those things affect lots of blog posts.]

**Comment by phil-opp** [comment]
> Unless I'm missing something master, since it contains all the features, sort of corresponds to the last post, or last post + potential next posts. So the last post -> master merge should be fairly easy, vs the master->first post backport having to "undo" all the intermediate posts.

I agree. I just don't want to reject pull requests that change code in the master branch. Also the `z_post_*` branches don't fit well into GitHub's pull request mechanism, since a pull request can only update a single branch. So the merges would need to be done either automatic, or by someone with push access if there are conflicts.

---

Let's just experiment with it and see what works best. I created initial `z_post_*` branches for the 9 posts and pushed the code for [post 1](https://github.com/phil-opp/blog_os/tree/z_post_01) and [post 2](https://github.com/phil-opp/blog_os/tree/z_post_02), the other branches just point to post 2 for now. I try to add the code for the other branches and some basic Readmes and CI scripts later. I would start with merging only the latest post into master for now.

--- 

> [FWIW, my skin in this really is the that latter sort of case, I really like your blog posts, and I'd love to offer PRs showing how to leverage proposals of mine like `extern existential type` or stdlib-aware Cargo if/when they are accepted and implemented. Those things affect lots of blog posts.]

That would be awesome!

**Comment by phil-opp** [comment]
So I finished implementing all the code for the `z_zost_*` branches and opened a pull request to merge `z_post_09` into master: https://github.com/phil-opp/blog_os/pull/538

I don't like the following things:

- The git history becomes very cluttered:
![image](https://user-images.githubusercontent.com/1131315/51750760-52173c00-20b3-11e9-91f7-dabac6cc24e7.png)

- Since the `z_post_*` branches have an unrelated history, git can only do a 2-way merge instead of a 3-way merge, so that automatic conflict resolution is not possible (even on the second merge).

**Comment by phil-opp** [comment]
I can see the following solutions:

- Base the `z_post_*` branches on the initial master commit instead of using unrelated histories. This allows git to do 3-way merges, but does not solve the cluttered history.
- Remove all code from `master` and link to the latest `z_post_*` branch from the Readme and/or add a git submodule in a `code` folder.
  - Advantages: Avoids the duplication between `master` and the latest `post` branch and would encourage people to open pull requests directly against the correct branch.
  - Drawbacks: New users might not find the code -> confusion. Contributing becomes more difficult.
- Handle the duplication manually: `cherry-pick` or `merge --squash` new commits from the latest post branch to `master` and from `master` to the post branches.
  - Advantage: Easy contribution, no problems finding the code, clean `master` history
  - Drawbacks: Manual work, a bit hacky

What do you think?

**Comment by Ericson2314** [comment]
> Since the `z_post_*` branches have an unrelated history, git can only do a 2-way merge instead of a 3-way merge, so that automatic conflict resolution is not possible (even on the second merge).

What do you mean by second merge? After you merge to master, the relevant part of the histories histories *will* be related (history before a common ancestor doesn't matter). So all future merges will work fine.

**Comment by Ericson2314** [comment]
Also, really excited you have the branches made :). Thanks for your interest in experimenting with all this!

**Comment by phil-opp** [comment]
> After you merge to master, the relevant part of the histories histories _will_ be related (history before a common ancestor doesn't matter). So all future merges will work fine.

I thought so too, but when I tried it I got the same "refusing to merge unrelated histories" error again. Maybe I did something wrong.

**Comment by Ericson2314** [comment]
Weird! Try merging back into `post-branches`? (if you `git merge --ff-only` `master` into `post-branches`, those will be identical, so this is a way to test what merging into `master` would be like.)

**Comment by phil-opp** [comment]
Seems like I did something wrong with the first merge. I tried it again and now git knows the history on the second merge.

**Comment by Ericson2314** [comment]
Whew! Glad to hear it!!
