### ISSUE TITLE
create_example_mapping

### ISSUE THREAD

**Issue by wwestlake** [phil-opp/blog_os#541]

**Comment by wwestlake** [comment]
EmptFrameAllocator won't compile.  The error indicated that the trait FrameAllocator needs to implement alloc:

```
error[E0407]: method `allocate_frame` is not a member of trait `FrameAllocator`
  --> hacker_os/src/memory.rs:9:5
   |
9  | /     fn allocate_frame(&mut self) -> Option<PhysFrame> {
10 | |         None
11 | |     }
   | |_____^ not a member of trait `FrameAllocator`

error[E0046]: not all trait items implemented, missing: `alloc`
 --> hacker_os/src/memory.rs:8:1
  |
8 | impl FrameAllocator<Size4KiB> for EmptyFrameAllocator {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `alloc` in implementation
  |
  = note: `alloc` from trait: `fn(&mut Self) -> core::option::Option<x86_64::structures::paging::PhysFrame<S>>`

```
I changed allocate_frame to alloc and it works.  Not sure if this is a version difference, I updated the rust nightly just before starting this chapter.

**Comment by phil-opp** [comment]
Ah, that's because I updated the blog [to `x86_64` 0.4.0](https://github.com/phil-opp/blog_os/commit/2cbe44ecefccef73a54903c8fea05bb381bb139c) a few days ago. It renamed the `alloc` method to `allocate_frame` (see the [Changelog](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md#040).

I added a note to the post in b9ff59f. Thanks for reporting!
