### ISSUE TITLE
What's the point?

### ISSUE THREAD

**Issue by mtbirdsall** [phil-opp/blog_os#558]
To be blunt, is the only purpose of rewriting an OS in rust to demonstrate that you can? Or to teach other's how to do it? 

I have thought of learning Rust, but as a hack programmer, I'm a bit lazy.  Although I have been super frustrated with how crappy current OS's are relative to advances in hardware. Not dumping memory, or crashing seems like a low bar, yet MacOS has progressively been getting worse in this area. I'm guessing you're not trying to make the UX better of my next-gen laptop... or are you?  

My dream of having a distraction-free coding experience and a smarter platform for productivity is slowly dying with 4k this and swiss-army-of-apps that. (We can't yet quantify how insane it is). If you told me I could build this with rust I would drop everything and do this with all my free time.  _If you have time to talk it would be great to get more information from you! And thanks, the content is great._

**Comment by rybot666** [comment]
This issue really went a bit over the top, didn't it? Not the creator, so I can't speak for him, but I think of it more as a learning experience than anything else tbh

**Comment by LinusU** [comment]
I'm not the creator either, but I think that this OS is mostly meant to teach others how to do it.

If you are looking for the next-gen OS that will make your next laptop greater, I would recommend looking into Redox OS: https://www.redox-os.org

**Comment by phil-opp** [comment]
@mtbirdsall Sorry for the late reply! As the others already said, teaching is the primary goal of this project. The idea is to get you started so that you can build your own small OS or contribute to existing projects such as Redox if you want to.

I understand that you are frustated with the state of current OSs. Of course it's _possible_ to build your dream OS in Rust, but writing an OS from scratch is an enourmous task, so it will take lots of time and work to get to the point where UX becomes important.

**Comment by phil-opp** [comment]
I think this is answered, therefore closing.
