### ISSUE TITLE
Rust as a Prerequisite

### ISSUE THREAD

**Issue by elliotmitchum** [phil-opp/blog_os#571]
I'm a CS student, just finished up my OS subject and I really want to explore further. I have read the first few posts and can follow the concepts, however I am kind of struggling to follow along with the Rust syntax. I'm wondering if it's recommended to first go through some material such as [the book](https://doc.rust-lang.org/stable/book/index.html) or if the content is / will be written in a way that doesn't assume too much Rust background?

**Comment by phil-opp** [comment]
I try my best to explain advanced Rust features when we use them or to at least provide some links. However, giving a complete introduction to Rust is out of scope for the blog. So I would recommend reading at least the first few chapters of the book if you are confused by the syntax.

Do you have any concrete questions? Maybe I can point you directly to the relevant chapters (or even add some links to the blog to help others too).

**Comment by AntoineSebert** [comment]
@elliotmitchum
I'm in the same situation, and I have made myself a bit familiar with the language's logic & syntax by attending hackathons (if you are free to pick the language you want of course) and by solving challenges online (plenty of websites, make your choice, just make sure that the `rustc` version is not too old, the language changed significantly during the past few years).

It may be easier if you are already comfortable with C/C++, however the safety concerns will bring you hard times.

All the (official ?) documentation you can find online is useful. Of course the Book is a must read, but don't forget [Rust by Example](https://doc.rust-lang.org/stable/rust-by-example/) and the [Standard Library](https://doc.rust-lang.org/std/index.html) (note for this last resource that is it not used, since this blog's aim is to create an OS, more info in the [first post](https://os.phil-opp.com/freestanding-rust-binary/)).

There's also a [discord server](https://discord.gg/rust-lang) if you're stuck.

**Comment by elliotmitchum** [comment]
@phil-opp I must say, you do explain the different Rust features very well and the links are very helpful.

I am running into trouble when trying to decipher what `Box::new` and `Box::leak` in [Unit Testing - Constructing a Writer](https://os.phil-opp.com/unit-testing/#constructing-a-writer) do. I don't understand what `&'static mut Buffer` means.

I have barely worked with manual memory management, so such things are new to me.

@AntoineSebert has mentioned some helpful resources, maybe it would be useful to add a "prerequisites" and/or "resources" section just in case people get stuck and to point out some assumed knowledge.

I'll go back and go through the book before going ahead.

I'll close this ticket as there isn't really anything actionable here, the advice has answered my initial question though. Thanks guys.

**Comment by AntoineSebert** [comment]
That's not a bad idea, although... the point of the blog is to create an OS from scratch, not your average program. It's supposed to be a very technical and complex task, therefore advanced knowledge in the choosen language is implicitly required, otherwise things can get complicated very quickly (I can relate).

It's even worse if you don't have experience with memory management, with years of practice I still don't understand what I'm doing sometimes (but thanks to the magic of programming, it may work).

And it's even "worser" because we have to use `unsafe` features quite often. Not only it's an advanced language feature, but it's not even a good practice: the purpose of Rust is to provide a fast and safe language to build applications.

If you're still here, I've tried to understand and explain the code you're struggling with (I really hope I didn't made any errors) :

According to ()[https://doc.rust-lang.org/std/boxed/struct.Box.html], a `Box` is just a pointer to a memory region (that can be anything) on the heap (dynamic memory).
It seems similar to a `smart_ptr` in C++, or a regular Java object. Or a `malloc/free` in C, but without the safety issues.
If you `leak()` the `Box`, you get a mutable reference to your allocated data. It's up to you to ensure the safety then, and, still from [struct.Box](https://doc.rust-lang.org/std/boxed/struct.Box.html) "Dropping the returned reference will cause a memory leak", because you will have an allocated region on the heap, but the reference to it will be lost (you don't know where it is anymore).

Concerning `&'static mut Buffer`, let's split it into parts:
- `&'static` : it's a reference to something (denoted by **&**) that lives during the "entire duration of the program", because of **'static** (from [](https://doc.rust-lang.org/book/ch10-03-lifetime-syntax.html#the-static-lifetime))
- `mut` : you can reallocate the data. By default in Rust, everything is imutable (inspired by functional programming)
- `Buffer` : you probably already know what a buffer is, but just in case : temporary memory region to store input/output data. In our context the datatype is `array_init(|_| array_init(|_| Volatile::new(empty_char())))`, aka two-dimensional array of `char`

**Comment by elliotmitchum** [comment]
@AntoineSebert That is a brilliant explanation. I can't thank you enough! I guess I have some long nights ahead of me :)
