### ISSUE TITLE
Use nested imports?

### ISSUE THREAD

**Issue by itmuckel** [phil-opp/blog_os#618]
Just a minor improvement: You could use [nested imports](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/nested-imports-with-use.html). For example I'm going through the Double Fault tutorial right now and the top of my `gdt.rs` currently looks like this:

```rust
use x86_64::{
    VirtAddr,
    structures::{
        gdt::{
            GlobalDescriptorTable,
            Descriptor,
            SegmentSelector,
        },
        tss::TaskStateSegment,
    },
};
use lazy_static::lazy_static;
```

Works everywhere where you can use `use`:
```rust
pub fn init() {
    use x86_64::instructions::{
        segmentation::set_cs,
        tables::load_tss,
    };

    GDT.0.load();
    unsafe {
        set_cs(GDT.1.code_selector);
        load_tss(GDT.1.tss_selector);
    }
}
```

PS: Thank you for taking away the hard parts of getting started with OS development! Couldn't imagine doing this stuff on my own!

**Comment by phil-opp** [comment]
Thanks for the suggestion! I often prefer nested imports myself too.

On the blog, however, the situation is a bit more difficult because we introduce the imports one after each other, so that grouping them would mean to repeat previous imports and making the code samples longer.

My current heuristic is to use nested imports only if multiple imports are added in the same step and if nested imports don't make the code samples longer. For example, the _Double Faults_ post uses the nested import

```rust
use x86_64::structures::gdt::{GlobalDescriptorTable, Descriptor};
```

but not the nested import

```rust
use x86_64::instructions::{
    segmentation::set_cs,
    tables::load_tss,
};
```

since the non-nested import

```
use x86_64::instructions::segmentation::set_cs;
use x86_64::instructions::tables::load_tss;
```

is one line shorter in this case.

> PS: Thank you for taking away the hard parts of getting started with OS development! Couldn't imagine doing this stuff on my own!

You're welcome! It's good to hear that the blog is useful to you!

**Comment by phil-opp** [comment]
I think we can close this issue. Let me know if you think otherwise, @itmuckel!
