### ISSUE TITLE
Cargo.toml build failed 

### ISSUE THREAD

**Issue by zeinali0** [phil-opp/blog_os#632]
I follow all step to Testing section. My codes build fine with `cargo xbuild` and it run well with `cargo xrun` but in `Cargo.toml` file i have some problem with this error 

> Could not compile `usize_conversions`.
process didn't exit successfully: `/home/ali/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rls --crate-name usize_conversions /home/ali/.cargo/registry/src/github.com-1ecc6299db9ec823/usize_conversions-0.2.0/src/lib.rs --color never --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=d398e8a816014e68 -C extra-filename=-d398e8a816014e68 --out-dir /home/ali/Projects/RustProjects/blog_os/target/rls/x86_64-blog_os/debug/deps --target x86_64-blog_os.json -L dependency=/home/ali/Projects/RustProjects/blog_os/target/rls/x86_64-blog_os/debug/deps -L dependency=/home/ali/Projects/RustProjects/blog_os/target/rls/debug/deps --cap-lints allow --error-format=json --sysroot /home/ali/.rustup/toolchains/stable-x86_64-unknown-linux-gnu` (exit code: 1)

and my rls dosen't work fine.

**Comment by 12101111** [comment]
Workaround available in #630

**Comment by phil-opp** [comment]
@zeinali0 The problem is that RLS uses the default sysroot, which you can see from the `--sysroot /home/ali/.rustup/toolchains/stable-x86_64-unknown-linux-gnu` argument in the error message. There isn't much that we can do from our side to fix it, but you can use one of the workarounds in #630 (as @12101111 suggested). Let me know if you still have problems then!
