### ISSUE TITLE
Build failing to build with latest x86_64 (0.7.2)

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#641]
So, apparently cargo is refusing to use version 0.7.2-beta0 of x86_64 and has happily jumped the gun to 0.7.2. Now rust is complaining that it can't find OffsetPageTable (see issue #640 for more info). Has this been renamed/removed?

**Comment by phil-opp** [comment]
The beta was a pre release of a pull request that is not merged yet. I try to merge it today and publish 0.7.3 with it. Sorry for the confusion!

In the meantime, you can force version  0.7.2-beta0 through `"= 0.7.2-beta0"`.

**Comment by ethindp** [comment]
I'm doing that, but its still forcing 0.7.2. I'll wait for the 0.7.3
release -- I should be awake by then.

On 7/11/19, Philipp Oppermann <notifications@github.com> wrote:
> The beta was a pre release of a pull request that is not merged yet. I try
> to merge it today and publish 0.7.3 with it. Sorry for the confusion!
>
> In the meantime, you can force version  0.7.2-beta0 through `"=
> 0.7.2-beta0"`.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/641#issuecomment-510343241


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
Not sure if I get to it today. We're having some CI problems because of https://github.com/rust-lang/rust/issues/62562, so I perhaps postpone it until the nightly is fixed again.

But you can still use the beta version, I just tried it. You need to specify an "[inequality requirement](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inequality-requirements)" using `=` for that:

```toml
x86_64 = "=0.7.2-beta.0"
```

Note the extra `=` inside the quotation marks.

**Comment by phil-opp** [comment]
I'm going to close this issue because it's a bit misleading for other readers. The project should build just fine with `0.7.2`, it just doesn't contain the `OffsetPageTable` from the beta version yet (which isn't used on the blog).

This doesn't mean that you can no longer comment here, it just removes this issue from the list of open issues.

**Comment by ethindp** [comment]
Thank you, I'll do that. I'm using rustc 1.37.0-nightly (0af8e872e
2019-06-30) so not sure why its breaking for me. I didn't think the
title would be misleading; sorry about that.

On 7/11/19, Philipp Oppermann <notifications@github.com> wrote:
> Closed #641.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/641#event-2475175469


-- 
Signed,
Ethin D. Probst
