### ISSUE TITLE
Its good but don't use third party libs. Try to solve everything by yourselfs

### ISSUE THREAD

**Issue by mobop** [phil-opp/blog_os#724]

**Comment by AntoineSebert** [comment]
@mobop I don't get it

**Comment by ethindp** [comment]
If your saying that you should never use 3rd-party libs... I have to say this is an utterly insane and ridiculous idea. Every program, excluding very specialized ones (i.e. spacecraft, aircraft, kernels in C, ...), has to use 3rd-party libraries to function. Hell,even kernels in C can use 3rd-party libraries (see LAI for example). Implementing everything manually is utterly insane and would, in corporate environments, raise development costs by a factor of about 30 or more. I propose the closure of this issue, if not the outright deletion of it... I cannot see any purpose in it unless tue author explains themselves.

**Comment by mobop** [comment]
@ethindp 
>If your saying that you should never use 3rd-party libs

no, i am not saying that. I saying when you are learning it is necessary to understand how you solve problems by yourself.
>in corporate environments, raise development costs by a factor of about 30 or more
again, this is for learning, not for making money.

**Comment by AntoineSebert** [comment]
@mobop I think that we should use 3rd party libraries so we can focus on learning the important aspects of OS crafting. There is no reason not to use libraries at this point. While @ethindp is a bit too categorical in my opinion, I agree with them.

**Comment by ethindp** [comment]
I know, I was a bit too categorical. And yes, this is a learning project for us who undertake it. However, libraries exist for a reason. Writing everything by hand is nice but can cause problems; for example, you may find yourself writing more libraries than OS code. Using the crates we have available to us to the fullest extent we can makes it possible for us to be more productive on our OSes and onlywrite what needs writing instead of writing literally everything.

**Comment by mobop** [comment]
library is used when there is a problem and the solution is already made. 
so if there is a problem, it is always better to know how to solve if by yourself. Again we are learning, not doing this to make money. It is important to understand every pieces, even though if it takes time.

**Comment by AntoineSebert** [comment]
> It is important to understand every pieces, even though if it takes time.

This is where we disagree. As of the last post at the moment, the dependencies list goes as follow:
- bootloader
- volatile
- spin
- x86_64
- uart_16550
- pic8259_simple
- pc-keyboard
- linked_list_allocator

Implementing all of those would require a dozen or more posts, while they have little to do with the actual creation of the OS. I understand your concern, but your advice is not applicable in the real world. If someone wants to learn, let's say, C++, by writing a little Nim game, should they start by implementing a compiler ?

Libraries provide the functionality we need through an API for a particular need, and therefore we focus on the problem we want to solve without paying attention to unecessary details or out-of-scope concerns.

But at the end of the day, the decision of whether to include or not a library is @phil-opp 's to take. So far I have nothing to complain about, he clearly knows what he's doing.

**Comment by ethindp** [comment]
This is my kernels current dependency list (its a bit longer). I have included descriptions for those that are not on @AntoineSebert's list. Do you really think I should write all of this myself?

* x86_64
* bootloader
* uart_16550
* volatile
* spin
* pic8259
* pc-keyboard
* cpuio: for function-like IN/OUT instructions
* bit_field: for manipulation of bit fields on 8, 16, 32, 64, and 128-bit integers
* slab_allocator: for memory allocation
* rusty-asm: for compile-time verification of asm! blocks
* goblin: for various binary format (executable code) parsers
* zerocopy: for zero-copy struct creation
* lazy_static

I'm telling you right now: I certainly have no idea how to implement things like spin or lazy_static properly. I'm not good with assembly either, and so implementing rusty-asm would be a pain and would take unnecessary time.

**Comment by mobop** [comment]
@ethindp,  if Don't know how to solve a problem that occurs during writing an os, Your learning is incomplete.

**Comment by ethindp** [comment]
@mobop your right, its incomplete. But I'm not going to implement all of those crates when people have already done it. That's a needless waste of time. That may be acceptable in C kernels, but definitely not in Rust. Hell, even kernels written in C/D/Go/whatever have libraries for them or have libs that can easilly be ported to those languages. No one is going to rewrite the entire C standard library, for instance, just to make a small game, if the game is for educational purposes, will they? They'll then be wasting more time fixing their custom cstdlib than actually programmign the game. So thanks but no thanks. I'll learn how to do it eventually, but I also like to be productive at the same time.

**Comment by bjorn3** [comment]
Should this series reimplement libcore? I think not. In my opinion this series should implement most things directly related to OS'es itself, while leaving everything that is not OS specific, like `lazy_static` and `once` to libraries. Also some device drivers are not worth re-implementing, as the core concepts used to talk to them (eg I/O ports, for qemu exit) are introduced elsewere and the rest is just some device specific details as opposed to things that matter for many devices or the core concepts too complex (DMA?) to explain at that stage of the series. Sometimes you have to simplify for things to be understandable. (use library) Then later you can explain it in more detail. (write yourself)

**Comment by phil-opp** [comment]
@mobop 

There is no such thing as "complete learning". There will always be details that you don't know because of the inherent complexity of computer systems, and that is perfectly okay. Nobody knows each detail of the x86 reference manual and more importantly, every undocumented detail of x86. Think of branch prediction: Even experts on the field did not know enough about the implementation of branch prediction to find the Spectre vulnerability for many years.

The very basic principle of computer systems is _abstraction_. A web developer does not need to know implementation details of Chrome/Firefox to write some Javascript code for a website. A browser developer does not need to know how the Linux kernel boots up or how the GPU driver is implemented. The Linux kernel developers does not need to know the `add` instruction is performed using logic gates on the CPU. Of course it sometimes helps to look behind an abstraction to some degree, but nobody would start a Javascript tutorial with an explanation about logic gates because it isn't useful to know these details at this point.

The reason I use libraries for the blog is similar: It allows us to abstract away unnecessary details. For example, the `bootloader` crate abstracts away the legacy boot process of `x86` because in my opinion there is little use in learning details of 16-bit real mode. Similarly, there is not much point in memorizing which keyboard keycode corresponds to each letter, so instead of writing the translation code ourselves, we simply use the abstraction provided by the `pc-keyboard` crate.

Another factor for using libraries in the blog is that it allows me to keep the posts moderately sized while still showing and explaining every line of code needed for the implementation. For example, it might be more interesting to you to write the page table manipulation functions yourself instead of using the `x86_64` crate, but it would make the post much much longer.

It's also important to remember that people are different. While some people might enjoy learning about all the details, other people prefer a higher level approach that only explains the concepts. There are also people that just get started with OS development and want to get started quickly. On the other hand, some more experienced people might prefer to write the implementation themselves instead of copying code from a tutorial. As you can imagine, it is not possible to create the perfect tutorial for all of these people. However, I think the use of libraries provides a good middle ground: Beginners can get started quickly, people that like more details can just look at the library implementation, and people that want to write the code themselves also profit from a shorter post with fewer details.

I hope this clarifies why the blog uses libraries. Since I don't plan to change this, I'm going to close this issue.

**Comment by mobop** [comment]
@phil-opp, thank you for your explanation.
