### ISSUE TITLE
Compare / contrast my VGA driver

### ISSUE THREAD

**Issue by steveklabnik** [phil-opp/blog_os#73]
Hey Phil,

Thanks again for a rad tutorial. I've been trying to do stuff on my own, while sort of peeking back at your stuff for hints. Given that 'print to the screen' is mostly Just Rust, I tried doing it myself. I figured opening an issue might be a decent way to discuss the differences, I'm not sure it's the right thing, let me know if I should have emailed you. :smile: 

Here's where I'm at: https://github.com/steveklabnik/nucleus/blob/cec875df64d988d707537c8058aa4862a532ef36/vga/src/lib.rs

The big difference, looking back, is in the way we built the buffer: I made mine a single, long buffer, and did calculations to get the x/y going. I also wrote a `flush()` that ends up doing the writing of the buffer to the screen, which is just a copy, since the buffer now has the same representation as the VGA memory itself.

Your code also handles long lines correctly; I'll have to fix mine to take this into account. I also don't need `Unique`, due to `flush()` handling it.

And I think I spotted another bug, I'm making the arrays twice as long as they need to be, now that they hold the struct rather than the bytes they did before...

Anyway. Would be interested in hearing your thoughts, or if I've done something else silly somewhere.

**Comment by steveklabnik** [comment]
Oh wait, they still do need to be twice as long...

**Comment by phil-opp** [comment]
Looks mostly good! I just tested it and wrapping works fine. And I think an array size of `CONSOLE_ROWS*CONSOLE_COLS` is correct, you just need to double the length in the `flush` function in line 91. (And I think that `CONSOLE_ROWS` could be 25 instead of 24.)

A problem is that you overwrite some other memory if the vga buffer is full (e.g. when printing 40 lines). But I think that could be handled by future scrolling code.

---

Your `flush` based approach has some cool advantages. For example, you could make the buffer bigger than the screen buffer to add some kind of history.

It has more overhead than directly writing to `0xb8000` since all lines are copied again for every `kprint`. But every scrolling code will need to copy the lines nonetheless, so I think it doesn't matter much.

**Comment by steveklabnik** [comment]
That's a good point. Thanks for checking it out!
