### ISSUE TITLE
zola build does not work to read offline 

### ISSUE THREAD

**Issue by adals** [phil-opp/blog_os#785]
hello 

thank you very much.

I wanted to read your blog locally so i did
cd blog_os/blog/

then zola serve it works great but

zola build and open public/index.html  it does not work

i got something like this

<img width="864" alt="Screen Shot 2020-04-05 at 11 16 08 AM" src="https://user-images.githubusercontent.com/169691/78470056-00deef80-772f-11ea-9678-12ea899a9f0d.png">

**Comment by bjorn3** [comment]
Run for example `python3 -m http.server 8080 public` and then go to `localhost:8080`.

All resources have a path relative to the domain the page is running on rather than relative to the path of the page itself. Eg the main css is referred to as `/css/main.css`, not `main.css` on the index page and `../main.css` on for example `/freestanding-rust-binary/` and `../../main.css` on for example `/status-update/2020-04-01/`.

Also I believe javascript won't load for pages on `file:///` for security reasons.

https://github.com/phil-opp/blog_os/blob/a237cd2777bd4ff518a9e2773702ce0f25c60bc5/blog/templates/second-edition/base.html#L16

**Comment by adals** [comment]
I got it

thanks for your answer
