### ISSUE TITLE
cargo test failed

### ISSUE THREAD

**Issue by sammyne** [phil-opp/blog_os#840]
When I playing around with [Testing](https://os.phil-opp.com/testing/) up to section [Custom Test Frameworks](https://os.phil-opp.com/testing/#custom-test-frameworks), it failed with following error

```bash
cargo test
   Compiling spin v0.5.2
   Compiling bootloader v0.9.8
   Compiling volatile v0.2.6
   Compiling rlibc v1.0.0
error: duplicate lang item in crate `core` (which `rustc_std_workspace_core` depends on): `bool`.
  |
  = note: the lang item is first defined in crate `core` (which `spin` depends on)
  = note: first definition in `core` loaded from /Users/lixiangmin01/Workspace/github.com/sammyne/blog-os-cn/04-testing/target/x86_64-blog_os/debug/deps/libcore-babf8101e728e9d7.rmeta
  = note: second definition in `core` loaded from /Users/lixiangmin01/Workspace/github.com/sammyne/blog-os-cn/04-testing/target/x86_64-blog_os/debug/deps/libcore-a79ed8b4326f3e01.rmeta

...
```

Reproduction code goes as [here](https://github.com/sammyne/blog-os-cn/tree/post-04/04-testing)

Desparate for help ~

**Comment by phil-opp** [comment]
This is a known issue with `-Z build-std` that occurs if you set panic to `abort` in your `Cargo.toml`: https://github.com/rust-lang/cargo/issues/7359

Try removing these lines: https://github.com/sammyne/blog-os-cn/blob/e2b65891acef94f9fb2cdd4d9b89e26b5035ad15/04-testing/Cargo.toml#L19-L23 . It will still be compiled with panic=abort even without these lines because you configured it [in your target json](https://github.com/sammyne/blog-os-cn/blob/e2b65891acef94f9fb2cdd4d9b89e26b5035ad15/04-testing/x86_64-blog_os.json#L12).

I'll add a note about this to the blog since it will likely affect many others too.

**Comment by phil-opp** [comment]
Note added in 4717834ad034e8da33d873b86b11e16c41d816d8.

**Comment by sammyne** [comment]
> This is a known issue with `-Z build-std` that occurs if you set panic to `abort` in your `Cargo.toml`: [rust-lang/cargo#7359](https://github.com/rust-lang/cargo/issues/7359)
> 
> Try removing these lines: https://github.com/sammyne/blog-os-cn/blob/e2b65891acef94f9fb2cdd4d9b89e26b5035ad15/04-testing/Cargo.toml#L19-L23 . It will still be compiled with panic=abort even without these lines because you configured it [in your target json](https://github.com/sammyne/blog-os-cn/blob/e2b65891acef94f9fb2cdd4d9b89e26b5035ad15/04-testing/x86_64-blog_os.json#L12).
> 
> I'll add a note about this to the blog since it will likely affect many others too.

The suggestion fix the problem!!!
Many thanks again 😄 @phil-opp
