### ISSUE TITLE
the trait `core::marker::Copy` is not implemented for `PageTableEntry`

### ISSUE THREAD

**Issue by brightzheng100** [phil-opp/blog_os#863]
This compilation error happens in `post-02`, `post-03`, and `post-04`:

```sh
$ cargo build
...
error[E0277]: the trait bound `PageTableEntry: core::marker::Copy` is not satisfied
   --> /Users/brightzheng/.cargo/registry/src/github.com-1ecc6299db9ec823/x86_64-0.11.0/src/structures/paging/page_table.rs:192:22
    |
192 |             entries: [PageTableEntry::new(); ENTRY_COUNT],
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `core::marker::Copy` is not implemented for `PageTableEntry`
    |
    = note: the `Copy` trait is required because the repeated element will be copied
...
```

, with the latest `nightly`:

```sh
$ rustc --version
rustc 1.48.0-nightly (0da580074 2020-09-22)
```

And the fix is quite simple, to update some impacted crates with a right version.

Let me know if a PR would help, or please fix it accordingly. Thank you!

**Comment by phil-opp** [comment]
Thanks for reporting. The blog posts should be updated for the new versions already (e.g. https://os.phil-opp.com/testing/#using-the-exit-device) and the `post-XX` branches should be too. Please let me know if I missed to update something.

There is also some breakage on the latest nightly, but it should just require a `cargo update`. In those cases (i.e. when no `Cargo.toml` update is needed), I typically don't update the posts since Cargo will automatically pick the latest compatible version.

**Comment by brightzheng100** [comment]
I'm quite confused about the `cargo update`. 

Let's take `post-04` as example:
```sh
$ git worktree add post-04 post-04 && cd post-04

# Here we can see exactly the version we define in cargo.toml
$ cargo tree
├── bootloader v0.9.8
├── lazy_static v1.4.0
│   └── spin v0.5.2
├── rlibc v1.0.0
├── spin v0.5.2
├── uart_16550 v0.2.7
│   ├── bitflags v1.2.1
│   └── x86_64 v0.11.0
│       ├── bit_field v0.9.0
│       └── bitflags v1.2.1
├── volatile v0.2.6
└── x86_64 v0.11.0 (*)

# Now we do a update and see some versions have been updated as per cargo's version convention "^xxx"
$ cargo update
    Updating crates.io index
    Updating bootloader v0.9.8 -> v0.9.11
    Updating uart_16550 v0.2.7 -> v0.2.9
    Updating volatile v0.2.6 -> v0.2.7
    Removing x86_64 v0.11.0
      Adding x86_64 v0.11.8
      Adding x86_64 v0.12.2
$ cargo tree
├── bootloader v0.9.11
├── lazy_static v1.4.0
│   └── spin v0.5.2
├── rlibc v1.0.0
├── spin v0.5.2
├── uart_16550 v0.2.9
│   ├── bitflags v1.2.1
│   └── x86_64 v0.12.2
│       ├── bit_field v0.9.0
│       └── bitflags v1.2.1
├── volatile v0.2.7
└── x86_64 v0.11.8
    ├── bit_field v0.9.0
    └── bitflags v1.2.1

# Let's try to build it but it would fail
$ cargo build
   Compiling compiler_builtins v0.1.35
   Compiling core v0.0.0 (/Users/brightzheng/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core)
   Compiling bitflags v1.2.1
   Compiling x86_64 v0.12.2
   Compiling x86_64 v0.11.8
   Compiling bootloader v0.9.11
   Compiling rustc-std-workspace-core v1.99.0 (/Users/brightzheng/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling bit_field v0.9.0
   Compiling spin v0.5.2
   Compiling rlibc v1.0.0
   Compiling volatile v0.2.7
   Compiling lazy_static v1.4.0
error[E0635]: unknown feature `const_fn_fn_ptr_basics`
 --> /Users/brightzheng/.cargo/registry/src/github.com-1ecc6299db9ec823/x86_64-0.12.2/src/lib.rs:7:43
  |
7 | #![cfg_attr(feature = "const_fn", feature(const_fn_fn_ptr_basics))]
  |                                           ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0635`.
error: could not compile `x86_64`
```

So as you can see, there would be two versions of 
- x86_64 v0.11.8: directly from explicit version declaration
- x86_64 v0.12.2: transitively from `uart_16550` v0.2.9

Typically how to resolve this issue in Cargo? I'm still learning

**Comment by brightzheng100** [comment]
Well, it works now after another `rustup update`.

Rust may be too dynamic and we need some luck to make it work:)

**Comment by phil-opp** [comment]
The problem you saw was a breaking change in the nightly Rust compiler itself that renamed the feature flag for an unstable feature. We updated all the libraries (including `x86_64`) to this new feature, but this only works if you're using the latest nightly that already knows the new feature flag name. Unfortunately there is no good solution to this, since it is not possible to write the code in a way that it compiles on both old and new nightlies.



> So as you can see, there would be two versions of
> 
>     * x86_64 v0.11.8: directly from explicit version declaration
> 
>     * x86_64 v0.12.2: transitively from `uart_16550` v0.2.9
> 
> 
> Typically how to resolve this issue in Cargo? I'm still learning

Cargo won't do automatic dependency updates where the first non-zero number in the version changes (e.g. 0.11.8 -> 0.12.2 or 1.1.0 -> 2.0.0), because such version changes are classified as potentially breaking. This means that you have to manually update the dependency version your `Cargo.toml` to switch to the latest version.

**Comment by brightzheng100** [comment]
Yes you’re right. And the versions with `0.x.y` are hard to handle so if `cargo update` wouldn’t help, we had to manually tune the version in `cargo.toml`
