### ISSUE TITLE
x86_64::instructions::interrupts::enable_interrupts_and_hlt deprecated

### ISSUE THREAD

**Issue by jhillyerd** [phil-opp/blog_os#889]
https://os.phil-opp.com/async-await/ will need to be updated to use [enable_and_hlt](https://docs.rs/x86_64/0.12.3/x86_64/instructions/interrupts/fn.enable_and_hlt.html) as [enable_interrupts_and_hlt](https://docs.rs/x86_64/0.12.3/x86_64/instructions/interrupts/fn.enable_interrupts_and_hlt.html) is deprecated.

**Comment by delta1** [comment]
Was this deprecated in v0.13.1 @phil-opp ? I’ll try put in a PR soon

**Comment by phil-opp** [comment]
This was deprecated in v0.12.3 and removed in v0.13.0. Given that v0.13.0 contains [many breaking changes](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md#0130--2020-12-28), it might be easier to just update to v0.12.4 first.

Unfortunately, updating this crate is a bit elaborate because we use it in a lot of places. We need to update all posts starting from "Testing" for the new version (including doc links) and also update the code in the `post-04` branch (the other `post-XX` branches can then be updated manually).

**Comment by delta1** [comment]
Sounds like a plan, 0.12.3 for the quickfix and then latest for the larger changes
