### ISSUE TITLE
Compile Error Because of Nightly Change

### ISSUE THREAD

**Issue by Rdna123** [phil-opp/blog_os#980]
`error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable` on **cpuio v3.0.0**

pic8259_simple holds the error for compiler
├── pic8259_simple v0.2.0
│   └── cpuio v0.3.0

I opened an issue on the [repository](https://github.com/emk/toyos-rs/issues/8#issue-877176919)

**Comment by phil-opp** [comment]
Thanks for reporting! I hope that this gets fixed in the upstream repo soon.

**Comment by CarlosLanderas** [comment]
If someone is interested, I managed to continue the tutorial (hardware interrupts part)
by using nightly  nightly-2021-03-15 and the following versions:

x86_64 = "0.13.6"
pic8259_simple = "0.2.0"

I get some deprecation warnings  for the x86-interrupt function signature as now takes a InterruptStackframe instead of a &mut InterruptStackFrame but I can continue :)

@phil-opp thanks for this amazing tutorial!

**Comment by phil-opp** [comment]
This should be fixed with https://github.com/phil-opp/blog_os/pull/990. Please let me know if you still have problems!

**Comment by CarlosLanderas** [comment]
I can confirm is working with latest nightly. Thanks!

**Comment by phil-opp** [comment]
Great to hear that, thanks for checking!
