### ISSUE TITLE
Compile error in VGA Buffer with Volatile

### ISSUE THREAD

**Issue by Rdna123** [phil-opp/blog_os#991]
```
rror[E0599]: the method `write` exists for struct `Volatile<ScreenChar>`, but its trait bounds were not satisfied
  --> src\vga_buffer.rs:97:45
   |
55 | struct ScreenChar {
   | -----------------
   | |
   | doesn't satisfy `<ScreenChar as Deref>::Target = _`
   | doesn't satisfy `ScreenChar: Deref`
...
97 |                 self.buffer.chars[row][col].write(ScreenChar {
   |                                             ^^^^^ method cannot be called on `Volatile<ScreenChar>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `<ScreenChar as Deref>::Target = _`
           `ScreenChar: Deref`

```

rustc --version
rustc 1.54.0-nightly (5c0292654 2021-05-11)

**Comment by bjorn3** [comment]
Which version of `volatile` are you using? Blog os uses version 0.2.6. The latest version 0.4.4 has a different api which I don't even think is correct due to requiring the creation of a mutable reference to the memory location you need to write to, which I think allows LLVM to insert spurious non-volatile reads and writes. Mixing non-volatile and volatile memory accesses allows for all accesses to be considered non-volatile.

**Comment by Rdna123** [comment]
Sorry, forgot to revert dependencies when I came a crossed the broken nightly error
